// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ZNwTTBMBQ9RsN0Rq2R5k7e7kFPw4GoA',
    appId: '1:1041276711558:web:5659fe9113b185e3d29707',
    messagingSenderId: '1041276711558',
    projectId: 'secsignal',
    authDomain: 'secsignal.firebaseapp.com',
    storageBucket: 'secsignal.appspot.com',
    measurementId: 'G-9MEY17456Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTt_hKd02WaVUbQ42YS0vL_sZvh2Xnk6w',
    appId: '1:1041276711558:android:c89accb2f2bdbcd9d29707',
    messagingSenderId: '1041276711558',
    projectId: 'secsignal',
    storageBucket: 'secsignal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6H2PN3jM78n2qrsWwhxJ3keHeCMaE_jM',
    appId: '1:1041276711558:ios:a5ff71ffa6392426d29707',
    messagingSenderId: '1041276711558',
    projectId: 'secsignal',
    storageBucket: 'secsignal.appspot.com',
    iosBundleId: 'com.friedman.secsignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6H2PN3jM78n2qrsWwhxJ3keHeCMaE_jM',
    appId: '1:1041276711558:ios:a5ff71ffa6392426d29707',
    messagingSenderId: '1041276711558',
    projectId: 'secsignal',
    storageBucket: 'secsignal.appspot.com',
    iosBundleId: 'com.friedman.secsignal',
  );
}
